# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Corne Base'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left", "corne_right"]'
      alphas: '["dvorak"]'
      custom_config: '["#define MIRYOKU_TAP_DVORAK"]'
      kconfig: '["CONFIG_ZMK_RGB_UNDERGLOW=y","CONFIG_WS2812_STRIP=y","CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=47","CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=70","CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=1"]'
